name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (Optional) Run workflow manually
  workflow_dispatch:
  # (Optional) Run workflow when pushing to master
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Output file name
          filename: github-metrics.svg
          
          # Options
          user: notamitgamer
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          
          # Plugin: Languages (Replaces your Top Langs)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          
          # Plugin: Streak (Replaces your Streak stats)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
